name: Code Style Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1

      - name: Install dependencies
        run: poetry install

      - name: flake8
        run: poetry run flake8 .

  code-style:
    name: Code Style Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1

      - name: Install dependencies
        run: poetry install

      - name: flake8
        run: poetry run flake8 .

      - name: black
        run: poetry run black --check .

      - name: isort
        run: poetry run isort --check .
