name: Code Style Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Restore dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: venv-${{ hashFiles('poetry.lock') }}
          restore-keys: venv-
      - name: Install dependencies
        run: poetry install
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: venv-${{ hashFiles('poetry.lock') }}
          restore-keys: venv-
  lint:
    name: Linting
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Restore dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: venv-${{ hashFiles('poetry.lock') }}
          restore-keys: venv-

      - name: flake8
        uses: ./actions/poetry-run
        with:
          cmd: flake8 .

  format:
    name: Formatting
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Restore dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: venv-${{ hashFiles('poetry.lock') }}
          restore-keys: venv-

      - name: black
        uses: ./actions/poetry-run
        with:
          cmd: black .
      - name: isort
        uses: ./actions/poetry-run
        with:
          cmd: isort .
