name: Code Style Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  setup:
    name: Setup up dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v4
      - name: Install dependencies
        run: poetry install
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.poetry
            ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: ls -hal ~
      - run: poetry
  lint:
    name: Linter
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: poetry run flake8
  format:
    name: Formatters
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - run: poetry run black .
      - run: poetry run isort .

  