name: Code Style Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Restore dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: venv-${{ hashFiles('poetry.lock') }}
          restore-keys: venv-


      - name: Install dependencies
        uses: ./.github/actions/run-in-container
        with:
          cmd: poetry install

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: venv-${{ hashFiles('poetry.lock') }}
          restore-keys: venv-
  lint:
    name: Linting
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: venv-${{ hashFiles('poetry.lock') }}
          restore-keys: venv-

      - name: flake8
        uses: ./.github/actions/run-in-container
        with:
          cmd: poetry run flake8 .

  format:
    name: Formatting
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: venv-${{ hashFiles('poetry.lock') }}
          restore-keys: venv-

      - name: black
        uses: ./.github/actions/run-in-container
        with:
          cmd: poetry run black .
      - name: isort
        uses: ./.github/actions/run-in-container
        with:
          cmd: poetry run isort .
