name: Code Style Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1

      - name: Install dependencies
        run: poetry install

      - name: flake8
        run: poetry run flake8 .

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1

      - name: Install dependencies
        run: poetry install

      - name: flake8
        run: poetry run flake8

      - name: black
        run: poetry run black .

      - name: isort
        run: poetry run isort .
