name: Code Style Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  code-pipeline:
    name: Linter+Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v4
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.poetry
            ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: poetry install
      - name: Run Formatter
        run: poetry run black . && poetry run isort .
      - name: Run linter
        run: poetry run flake8 .
